library(BiocManager)
options(repos = BiocManager::repositories())
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(plotly)
library(HTSet)
library(DT)
library(ggfortify)
# library(shinyauthr)
# library(shinyjs)
# library(shiny.router)
# library(enrichplot)
# library(biomaRt)
# library(org.Hs.eg.db)
library(ggpubr)

dashboardHeader = eval(parse(text = deparse(shinydashboard::dashboardHeader)[-5]))

reactome <- readRDS("data/glyco_reactome.rds") %>%
    dplyr::rename(ensembl_gene_id = Ensembl)
DE_mayo <- readRDS("data/DE_mayo_adj.rds")
logcpm_mayo <- readRDS("data/mayo_normalized_adj.rds")
DE_msbb <- readRDS("data/DE_msbb_adj.rds")
logcpm_msbb <- readRDS("data/msbb_normalized_adj.rds")
DE <- readRDS("data/DE_rosmap_adj.rds")
logcpm <- readRDS("data/rosmap_normalized_adj.rds")
